blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog-bejegyzesek'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('add/gift/<int:card_id>', views.cart_add_gift_card, name='cart_add_gift_card'),
    path('remove/<int:item_id>', views.cart_remove, name='cart_remove'),
    path('cart_remove_giftcard/<int:id>', views.cart_remove_giftcard, name='cart_remove_giftcard'),
]

counter/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

# handler404 = 'shop.views.view_404'

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('order/', include('order.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('giftcard-payment/', include('giftcardpayment.urls', namespace='giftcardpayment')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.generic import TemplateView

from blog.sitemaps import BlogCategorySitemap, PostSitemap
from parameters.models import Parameter
from . import views
from .sitemaps import StaticViewsSitemap, CollectionSitemap, ProductSitemap

sitemaps = {
    'static': StaticViewsSitemap,
    'product': ProductSitemap,
    'collection': CollectionSitemap,
    'post': PostSitemap
}

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('termekek/', views.ProductsView.as_view(), name='products_view'),
    path('slowstudio/', views.StudioProductsView.as_view(), name='studio_products_view'),
    path('termekek/<str:slug>', views.ProductsView.as_view(), name='products_view'),
    path('termek/<str:id>/<str:slug>', views.product_detail, name='product_detail'),
    path('slowstudiotermek/<str:id>/<str:slug>', views.studio_product_detail, name='studio_product_detail'),
    path('gyik', views.faq, name='faq'),
    path('kapcsolat/', views.contact, name='contact'),
    path('aszf/', views.aszf, name='aszf'),
    path('adatvedelem/', views.data_handling, name='data_handling'),
    path('uzenet/', views.contact_message, name='contact_message'),
    path('sikeres-uzenet-kuldes/', views.thank_you, name='thank_you'),
    path('impresszum/', views.impresszum, name='impresszum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="shop/robots.txt", content_type='text/plain')),
    path('icon/', views.get_icon, name='get_icon'),
    path('generate_stripe_product/<str:id>', views.generate_stripe_product, name='generate_stripe_product'),
    path('termekek/kereses/', views.SearchProductsView.as_view(), name='products_view_search'),
    path('name-validation/<str:name>', views.name_validation, name='name-validation'),
    path('price-api-key/<str:price>', views.price_api_key, name='price-api-key'),
]

if Parameter.objects.filter(name="custom_service")[0].value == 'True':
    urlpatterns.extend([
        path('egyedi-rendelés/', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-rendelés/<str:slug>', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-termek/<str:id>/<str:slug>', views.custom_product_detail, name='custom_product_detail')
    ])

shop/forms.py
from django import forms
from django.forms import ModelForm

from .models import Message


class ContactForm(ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'email', 'message', 'name']
        widgets = dict(subject=forms.HiddenInput, email=forms.HiddenInput,
                       message=forms.HiddenInput, name=forms.HiddenInput)

shop/views.py
import json
import logging
import os
import re

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Case, When
from django.db.utils import OperationalError
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import redirect, reverse
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.views.generic.list import ListView

from cart.forms import CartAddProductForm, CartAddCustomProductForm, CartAddGiftCardProductForm
from parameters.models import Parameter
from shop.MessageSender import MessageSender
from .StripeProductGenerator import StripeProductGenerator
from .forms import ContactForm
from .models import Collection, Product, Notification, ProductType, GiftCard, Message

stripe_product_generator = StripeProductGenerator()
log = logging.getLogger(__name__)


def mobile(request):
    MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)
    if 'HTTP_USER_AGENT' in request.META and MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False


def index_hid(request):
    return render(request, 'shop/index.html')


def index(request):
    coll = Collection.objects.filter(available=True, custom=False, show_on_home_page=True)
    basic_collection = [c for c in coll if c.basic_collection and not c.best_seller_collection]
    temp = [c for c in coll if c.regular_collection and not c.best_seller_collection]
    regular_collections = sorted(temp, key=lambda x: x.created, reverse=True)[:3]
    temp = [c for c in coll if not c.basic_collection and not c.regular_collection and not c.best_seller_collection]
    temporary_collections = sorted(temp, key=lambda x: x.created, reverse=True)[:9]
    temp = [c for c in coll if c.best_seller_collection]
    best_sellers_collection = sorted(temp, key=lambda x: x.created)
    # basic_collection = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                              basic_collection=True, best_seller_collection=False)
    if len(basic_collection):
        basic_products = Product.objects.filter(collection=basic_collection[0])
    else:
        basic_products = []
    # regular_collections = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                                 regular_collection=True, best_seller_collection=False).order_by('-created')[:3]
    # temporary_collections = (
    #     Collection.objects.filter(available=True, custom=False, show_on_home_page=True, basic_collection=False,
    #                               regular_collection=False, best_seller_collection=False)
    #         .order_by('-created')[:9])
    # best_sellers_collection = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                                     best_seller_collection=True).order_by('-created')
    if len(best_sellers_collection):
        bs_products = Product.objects.filter(collection=best_sellers_collection[0])
    else:
        bs_products = []
    notification = Notification.objects.all()
    is_mobile = mobile(request)
    param = Parameter.objects.filter(name="shipping_information")
    shipping_information = param[0].value if len(param) and param[0].active else None
    ratio = 0.93 if is_mobile else 2.44
    context = dict(basic_collection=basic_collection, basic_products=basic_products,
                   regular_collections=regular_collections, temporary_collections=temporary_collections,
                   notification=notification, ratio=ratio, shipping_information=shipping_information,
                   best_sellers_collection=best_sellers_collection, bs_products=bs_products, device=mobile(request))
    return render(request, 'shop/index_hid.html', context)


def __get_product_details(request, id: str, slug: str, custom: bool, studio: bool, referer: str):
    old_collection = False
    try:
        collection = Collection.objects.filter(slug=id)[0]
    except (Collection.DoesNotExist, IndexError):
        log.info(f'Exception in getting product details - Collection slug {id}')
        return render(request, 'shop/404_termek.html', {})
    try:
        product = Product.objects.filter(collections=collection.id, slug=slug, available=True, custom=custom)[0]
    except (Product.DoesNotExist, IndexError):
        product = Product.objects.filter(collection=collection, slug=slug, available=True, custom=custom)
        if not len(product):
            log.info(f'Exception in getting product details - Product slug {slug}')
            return render(request, 'shop/404_termek.html', {})
        else:
            old_collection = True
            product = product[0]
    if old_collection:
        product_types = Product.objects.prefetch_related('product_types').filter(collection=collection, slug=slug,
                                                                                 available=True, custom=custom)
        images = Product.objects.prefetch_related('images').filter(collection=collection, slug=slug, available=True,
                                                                   custom=custom)
    else:
        product_types = Product.objects.prefetch_related('product_types').filter(collections=collection.id, slug=slug,
                                                                                 available=True, custom=custom)
        images = Product.objects.prefetch_related('images').filter(collections=collection.id, slug=slug, available=True,
                                                                   custom=custom)
    imgs = images[0].images.all()
    types = product_types[0].product_types.all()
    is_stock = False
    if types:
        for type in types:
            if type.stock > 0:
                is_stock = True
                break
    else:
        if product.stock > 0:
            is_stock = True
    cart_product_form = CartAddCustomProductForm() if custom else CartAddProductForm()
    basic_collections = [] if studio else Collection.objects.filter(
        available=True, basic_collection=True, custom=custom, studio_collection=False).order_by('-created')
    regular_collections = [] if studio else Collection.objects.filter(available=True, custom=custom,
                                                                      regular_collection=True,
                                                                      studio_collection=False).order_by('-created')
    temporary_collections = [] if studio else Collection.objects.filter(available=True, custom=custom,
                                                                        basic_collection=False,
                                                                        regular_collection=False,
                                                                        best_seller_collection=False,
                                                                        studio_collection=False).order_by('-created')
    # find if there is utolsó darabok
    temp = list(temporary_collections)
    upper = [e.name for e in temp if e.name.isupper()]
    if len(upper):
        idx_of_upper = [idx for idx, u in enumerate(temp) if u.name == upper[0]][0]
        temp.append(temp.pop(idx_of_upper))
    notification = Notification.objects.all()
    collection_slug = '' if studio else product.get_collection_slug()
    view = 'shop:studio_products_view' if studio else ('shop:custom_products_view' if custom else 'shop:products_view')
    template = 'shop/product/custom_detail.html' if custom else 'shop/product/detail.html'
    param = Parameter.objects.filter(name="shipping_information")
    nemes_acel = Parameter.objects.filter(name="nemesacel_beszuro")[0].value
    muanyag = Parameter.objects.filter(name="muanyag_beszuro")[0].value
    nikkel_mentes = Parameter.objects.filter(name="nikkel_mentes")[0].value
    shipping_information = param[0].value if len(param) and param[0].active else None
    if referer == settings.MAIN_URL or referer is None:
        if studio:
            referer = settings.MAIN_URL + 'slowstudio'
        else:
            referer = settings.MAIN_URL + 'termekek/' + product.get_collection_slug()
    return render(request, template,
                  {'product': product,
                   'notification': notification,
                   'basic_collections': basic_collections,
                   'regular_collections': regular_collections,
                   'temporary_collections': temp,
                   'collection_slug': collection_slug,
                   'types': types,
                   'cart_product_form': cart_product_form,
                   'is_stock': is_stock,
                   'images': imgs,
                   'view': view,
                   'slug': collection_slug,
                   'shipping_information': shipping_information,
                   'nemes_acel': nemes_acel,
                   'muanyag': muanyag,
                   'nikkel_mentes': nikkel_mentes,
                   'referer': referer,
                   'device': mobile(request)
                   })


def product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, False, False, referer)


def studio_product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, False, True, referer)


def custom_product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, True, False, referer)


def faq(request):
    foxpost = Parameter.objects.filter(name="foxpost_price")[0].value
    delivery = Parameter.objects.filter(name="delivery_price")[0].value

shop/templates/shop/headers/desktop.html
{% load static %}
<div class="row">
    <div class="col-md-12">
        <div id="search-bar">
            <form method="GET" action="{% url 'shop:products_view_search' %}">
                <input class="form-control" type="search" placeholder="Keresés (név, szín, minta)"
                       aria-label="Search" name="kulcsszo" maxlength="50" pattern="[a-z áéúőóüö A-Z ÁÉÚŐÓÜÖ]*"
                       title="Kérlek, csak betűket használj!" minlength="3">
                <button id="search-submit-button" type="submit"></button>
            </form>
        </div>
        <div id="main-logo">
            <a href="{% url 'shop:index' %}">
                <picture>
                    <source class="c_logo" srcset="{% static 'images/logo_150.webp' %}" type="image/webp">
                    <img class="c_logo" src="{% static 'images/logo_150.png' %}" alt="Minerva Studio Logo"
                         title="Minerva Studio Logo image" width="265" height="137"/>
                </picture>
            </a>
        </div>
        <div id="cart-icon-wrapper">
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
            <a href="{% url 'cart:cart_detail' %}">
                {% with total_items_plural=total_items|pluralize %}
                <div class="item-in-cart-indicator"><span>{{ total_items }}</span></div>
                <picture>
                    <source class="c_logo" srcset="{% static 'images/cart_150.webp' %}" type="image/webp">
                    <img class="c_logo" src="{% static 'images/cart_150.png' %}" alt="Minerva Studio Cart Icon"
                         title="Minerva Studio Cart Icon" width="50" height="50"/>
                </picture>
                {% endwith %}
            </a>
            {% else %}
            <div class="cart-icon-inner">
                <picture>
                    <source class="c_logo" srcset="{% static 'images/cart_150.webp' %}" type="image/webp">
                    <img class="c_logo" src="{% static 'images/cart_150.png' %}" alt="Minerva Studio kosár ikon"
                         title="Minerva Studio kosár ikon" width="50" height="50"/>
                </picture>
            </div>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</div>
<div class="row desktop-menu">
    <div class="navigation">
        <ul class="mainmenu">
            <li class="{% if request.path == '/' %}current{% endif %} menu-item">
                <a title="Kezdőlap" href="{% url 'shop:index' %}">Kezdőlap</a>
            </li>
            <li class="{% if '/termek' in request.path %}current{% endif %} menu-item">
                <a title="Termékek" href="{% url 'shop:products_view' %}">Termékek</a>
            </li>
            <li class="{% if '/gyik' in request.path %}current{% endif %} menu-item">
                <a title="GYIK" href="{% url 'shop:faq' %}">GYIK</a>
            </li>
            <li class="{% if '/kapcsolat' in request.path %}current{% endif %} menu-item">
                <a title="Kapcsolat" href="{% url 'shop:contact' %}">Kapcsolat</a>
            </li>
            <li class="{% if request.path == '/blog/' %}current{% endif %} menu-item">
                <a title="Blog" href="{% url 'blog:blog-bejegyzesek' %}">Blog</a>
            </li>
            {% if CUSTOM %}
            <li class="{% if '/egyedi-rendelés' in request.path %}current{% endif %} menu-item">
                <a title="Kapcsolat" href="{% url 'shop:custom_products_view' %}">Egyedi rendelés</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

shop/templates/shop/headers/mobile.html
{% load static %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-6">
                <div id="main-logo">
                    <a href="{% url 'shop:index' %}">
                        <picture>
                            <source class="c_logo" srcset="{% static 'images/logo_150.webp' %}" type="image/webp">
                            <img class="c_logo" src="{% static 'images/logo_150.png' %}" alt="Minerva Studio Logo"
                                 title="Minerva Studio Logo image" width="265" height="137"/>
                        </picture>
                    </a>
                </div>
            </div>
            <div class="col-6 mobile-icons-col">
                <div class="mobile-icons-wrapper">
                    <div id="cart-icon-wrapper-mobile">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                        <a href="{% url 'cart:cart_detail' %}">
                            {% with total_items_plural=total_items|pluralize %}
                            <div class="item-in-cart-indicator"><span>{{ total_items }}</span></div>
                            <picture>
                                <source class="c_logo" srcset="{% static 'images/cart_150.webp' %}" type="image/webp">
                                <img class="c_logo" src="{% static 'images/cart_150.png' %}"
                                     alt="Minerva Studio Cart Icon"
                                     title="Minerva Studio Cart Icon" width="50" height="50"/>
                            </picture>
                            {% endwith %}
                        </a>
                        {% else %}
                        <div class="cart-icon-inner">
                            <picture>
                                <source class="c_logo" srcset="{% static 'images/cart_150.webp' %}" type="image/webp">
                                <img class="c_logo" src="{% static 'images/cart_150.png' %}"
                                     alt="Minerva Studio kosár ikon"
                                     title="Minerva Studio kosár ikon" width="50" height="50"/>
                            </picture>
                        </div>
                        {% endif %}
                        {% endwith %}
                    </div>
                    <div class="search-icon-wrapper">
                        <picture>
                            <source class="c_search" srcset="{% static 'images/search-01.webp' %}" type="image/webp">
                            <img class="c_search" src="{% static 'images/search-01.png' %}"
                                 alt="Minerva Studio keresés ikon"
                                 title="Minerva Studio keresés ikon" width="50" height="50"/>
                        </picture>
                    </div>
                    <div id="mobile-menu-wrapper">
                        <div id="menu-btn"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 mobile-menu">
        <div class="navigation">
            <div id="mobile-menu-close"></div>
            <ul class="mainmenu">
                <li class="{% if request.path == '/' %}current{% endif %} menu-item">
                    <a title="Kezdőlap" href="{% url 'shop:index' %}">Kezdőlap</a>
                </li>
                <li class="{% if '/termek' in request.path %}current{% endif %} menu-item">
                    <a title="Termékek" href="{% url 'shop:products_view' %}">Termékek</a>
                </li>
                <li class="{% if '/gyik' in request.path %}current{% endif %} menu-item">
                    <a title="GYIK" href="{% url 'shop:faq' %}">GYIK</a>
                </li>
                <li class="{% if '/kapcsolat' in request.path %}current{% endif %} menu-item">
                    <a title="Kapcsolat" href="{% url 'shop:contact' %}">Kapcsolat</a>
                </li>
                <li class="{% if request.path == '/blog/' %}current{% endif %} menu-item">
                    <a title="Blog" href="{% url 'blog:blog-bejegyzesek' %}">Blog</a>
                </li>
                {% if CUSTOM %}
                <li class="{% if '/egyedi-rendelés' in request.path %}current{% endif %} menu-item">
                    <a title="Kapcsolat" href="{% url 'shop:custom_products_view' %}">Egyedi rendelés</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<div id="search-bar-wrapper">
    <div id="search-bar-close"></div>
    <div id="search-bar">
        <form method="GET" action="{% url 'shop:products_view_search' %}">
            <input class="form-control" type="search" placeholder="Keresés (név, szín, minta)"
                   aria-label="Search" name="kulcsszo" maxlength="50" pattern="[a-z áéúőóüö A-Z ÁÉÚŐÓÜÖ]*"
                   title="Kérlek, csak betűket használj!" minlength="3">
            <button id="search-submit-button" type="submit"></button>
        </form>
    </div>
</div>