blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog-bejegyzesek'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('add/gift/<int:card_id>', views.cart_add_gift_card, name='cart_add_gift_card'),
    path('remove/<int:item_id>', views.cart_remove, name='cart_remove'),
    path('cart_remove_giftcard/<int:id>', views.cart_remove_giftcard, name='cart_remove_giftcard'),
]

counter/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

# handler404 = 'shop.views.view_404'

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('order/', include('order.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('giftcard-payment/', include('giftcardpayment.urls', namespace='giftcardpayment')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.generic import TemplateView

from blog.sitemaps import BlogCategorySitemap, PostSitemap
from parameters.models import Parameter
from . import views
from .sitemaps import StaticViewsSitemap, CollectionSitemap, ProductSitemap

sitemaps = {
    'static': StaticViewsSitemap,
    'product': ProductSitemap,
    'collection': CollectionSitemap,
    'post': PostSitemap
}

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('termekek/', views.ProductsView.as_view(), name='products_view'),
    path('slowstudio/', views.StudioProductsView.as_view(), name='studio_products_view'),
    path('termekek/<str:slug>', views.ProductsView.as_view(), name='products_view'),
    path('termek/<str:id>/<str:slug>', views.product_detail, name='product_detail'),
    path('slowstudiotermek/<str:id>/<str:slug>', views.studio_product_detail, name='studio_product_detail'),
    path('gyik', views.faq, name='faq'),
    path('kapcsolat/', views.contact, name='contact'),
    path('aszf/', views.aszf, name='aszf'),
    path('adatvedelem/', views.data_handling, name='data_handling'),
    path('uzenet/', views.contact_message, name='contact_message'),
    path('sikeres-uzenet-kuldes/', views.thank_you, name='thank_you'),
    path('impresszum/', views.impresszum, name='impresszum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="shop/robots.txt", content_type='text/plain')),
    path('icon/', views.get_icon, name='get_icon'),
    path('generate_stripe_product/<str:id>', views.generate_stripe_product, name='generate_stripe_product'),
    path('termekek/kereses/', views.SearchProductsView.as_view(), name='products_view_search'),
    path('name-validation/<str:name>', views.name_validation, name='name-validation'),
    path('price-api-key/<str:price>', views.price_api_key, name='price-api-key'),
]

if Parameter.objects.filter(name="custom_service")[0].value == 'True':
    urlpatterns.extend([
        path('egyedi-rendelés/', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-rendelés/<str:slug>', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-termek/<str:id>/<str:slug>', views.custom_product_detail, name='custom_product_detail')
    ])

shop/forms.py
from django import forms
from django.forms import ModelForm

from .models import Message


class ContactForm(ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'email', 'message', 'name']
        widgets = dict(subject=forms.HiddenInput, email=forms.HiddenInput,
                       message=forms.HiddenInput, name=forms.HiddenInput)

shop/views.py
import json
import logging
import os
import re

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Case, When
from django.db.utils import OperationalError
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import redirect, reverse
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.views.generic.list import ListView

from cart.forms import CartAddProductForm, CartAddCustomProductForm, CartAddGiftCardProductForm
from parameters.models import Parameter
from shop.MessageSender import MessageSender
from .StripeProductGenerator import StripeProductGenerator
from .forms import ContactForm
from .models import Collection, Product, Notification, ProductType, GiftCard, Message

stripe_product_generator = StripeProductGenerator()
log = logging.getLogger(__name__)


def mobile(request):
    MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)
    if 'HTTP_USER_AGENT' in request.META and MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False


def index_hid(request):
    return render(request, 'shop/index.html')


def index(request):
    coll = Collection.objects.filter(available=True, custom=False, show_on_home_page=True)
    basic_collection = [c for c in coll if c.basic_collection and not c.best_seller_collection]
    temp = [c for c in coll if c.regular_collection and not c.best_seller_collection]
    regular_collections = sorted(temp, key=lambda x: x.created, reverse=True)[:3]
    temp = [c for c in coll if not c.basic_collection and not c.regular_collection and not c.best_seller_collection]
    temporary_collections = sorted(temp, key=lambda x: x.created, reverse=True)[:9]
    temp = [c for c in coll if c.best_seller_collection]
    best_sellers_collection = sorted(temp, key=lambda x: x.created)
    # basic_collection = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                              basic_collection=True, best_seller_collection=False)
    if len(basic_collection):
        basic_products = Product.objects.filter(collection=basic_collection[0])
    else:
        basic_products = []
    # regular_collections = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                                 regular_collection=True, best_seller_collection=False).order_by('-created')[:3]
    # temporary_collections = (
    #     Collection.objects.filter(available=True, custom=False, show_on_home_page=True, basic_collection=False,
    #                               regular_collection=False, best_seller_collection=False)
    #         .order_by('-created')[:9])
    # best_sellers_collection = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                                     best_seller_collection=True).order_by('-created')
    if len(best_sellers_collection):
        bs_products = Product.objects.filter(collection=best_sellers_collection[0])
    else:
        bs_products = []
    notification = Notification.objects.all()
    is_mobile = mobile(request)
    param = Parameter.objects.filter(name="shipping_information")
    shipping_information = param[0].value if len(param) and param[0].active else None
    ratio = 0.93 if is_mobile else 2.44
    context = dict(basic_collection=basic_collection, basic_products=basic_products,
                   regular_collections=regular_collections, temporary_collections=temporary_collections,
                   notification=notification, ratio=ratio, shipping_information=shipping_information,
                   best_sellers_collection=best_sellers_collection, bs_products=bs_products, device=mobile(request))
    return render(request, 'shop/index_hid.html', context)


def __get_product_details(request, id: str, slug: str, custom: bool, studio: bool, referer: str):
    old_collection = False
    try:
        collection = Collection.objects.filter(slug=id)[0]
    except (Collection.DoesNotExist, IndexError):
        log.info(f'Exception in getting product details - Collection slug {id}')
        return render(request, 'shop/404_termek.html', {})
    try:
        product = Product.objects.filter(collections=collection.id, slug=slug, available=True, custom=custom)[0]
    except (Product.DoesNotExist, IndexError):
        product = Product.objects.filter(collection=collection, slug=slug, available=True, custom=custom)
        if not len(product):
            log.info(f'Exception in getting product details - Product slug {slug}')
            return render(request, 'shop/404_termek.html', {})
        else:
            old_collection = True
            product = product[0]
    if old_collection:
        product_types = Product.objects.prefetch_related('product_types').filter(collection=collection, slug=slug,
                                                                                 available=True, custom=custom)
        images = Product.objects.prefetch_related('images').filter(collection=collection, slug=slug, available=True,
                                                                   custom=custom)
    else:
        product_types = Product.objects.prefetch_related('product_types').filter(collections=collection.id, slug=slug,
                                                                                 available=True, custom=custom)
        images = Product.objects.prefetch_related('images').filter(collections=collection.id, slug=slug, available=True,
                                                                   custom=custom)
    imgs = images[0].images.all()
    types = product_types[0].product_types.all()
    is_stock = False
    if types:
        for type in types:
            if type.stock > 0:
                is_stock = True
                break
    else:
        if product.stock > 0:
            is_stock = True
    cart_product_form = CartAddCustomProductForm() if custom else CartAddProductForm()
    basic_collections = [] if studio else Collection.objects.filter(
        available=True, basic_collection=True, custom=custom, studio_collection=False).order_by('-created')
    regular_collections = [] if studio else Collection.objects.filter(available=True, custom=custom,
                                                                      regular_collection=True,
                                                                      studio_collection=False).order_by('-created')
    temporary_collections = [] if studio else Collection.objects.filter(available=True, custom=custom,
                                                                        basic_collection=False,
                                                                        regular_collection=False,
                                                                        best_seller_collection=False,
                                                                        studio_collection=False).order_by('-created')
    # find if there is utolsó darabok
    temp = list(temporary_collections)
    upper = [e.name for e in temp if e.name.isupper()]
    if len(upper):
        idx_of_upper = [idx for idx, u in enumerate(temp) if u.name == upper[0]][0]
        temp.append(temp.pop(idx_of_upper))
    notification = Notification.objects.all()
    collection_slug = '' if studio else product.get_collection_slug()
    view = 'shop:studio_products_view' if studio else ('shop:custom_products_view' if custom else 'shop:products_view')
    template = 'shop/product/custom_detail.html' if custom else 'shop/product/detail.html'
    param = Parameter.objects.filter(name="shipping_information")
    nemes_acel = Parameter.objects.filter(name="nemesacel_beszuro")[0].value
    muanyag = Parameter.objects.filter(name="muanyag_beszuro")[0].value
    nikkel_mentes = Parameter.objects.filter(name="nikkel_mentes")[0].value
    shipping_information = param[0].value if len(param) and param[0].active else None
    if referer == settings.MAIN_URL or referer is None:
        if studio:
            referer = settings.MAIN_URL + 'slowstudio'
        else:
            referer = settings.MAIN_URL + 'termekek/' + product.get_collection_slug()
    return render(request, template,
                  {'product': product,
                   'notification': notification,
                   'basic_collections': basic_collections,
                   'regular_collections': regular_collections,
                   'temporary_collections': temp,
                   'collection_slug': collection_slug,
                   'types': types,
                   'cart_product_form': cart_product_form,
                   'is_stock': is_stock,
                   'images': imgs,
                   'view': view,
                   'slug': collection_slug,
                   'shipping_information': shipping_information,
                   'nemes_acel': nemes_acel,
                   'muanyag': muanyag,
                   'nikkel_mentes': nikkel_mentes,
                   'referer': referer,
                   'device': mobile(request)
                   })


def product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, False, False, referer)


def studio_product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, False, True, referer)


def custom_product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, True, False, referer)


def faq(request):
    foxpost = Parameter.objects.filter(name="foxpost_price")[0].value
    delivery = Parameter.objects.filter(name="delivery_price")[0].value

shop/templates/shop/product/custom_list.html
{% include "shop/base.html" with notification=notification product_list=True notfound=False device=device %}
{% load static %}

{% block content %}
<div class="content product-list">
    <div class="container-fluid">
        <div class="row list-filter-row">
            <div id="detail-page-filter-button"></div>
            <div class="col-sm-3 list-page-filter">
                <div id="mobile-filter-close"></div>
                {% include 'shop/product/filter.html' %}
            </div>
            <div class="col-sm-9">
                <div id="products-wrapper">
                    {% for product in custom_products %}
                    <div class="product-element">
                        <div class="product-element-image-wrapper">
                            {% if product.image %}
                            <a href="{% url 'shop:custom_product_detail' id=product.get_collection_slug slug=product.slug %}" title="Termék oldal">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" title="{{ product.name }}"
                                     class="product-element-image"/>
                                {% endif %}
                                <img src="{% static 'images/sold_out_150.png' %}" alt="Elfogyott" title="Elfogyott"
                                     class="sold-out-icon"/>
                            </a>
                        </div>
                        <div class="product-element-description-wrapper">
                            <a href="{% url 'shop:custom_product_detail' id=product.get_collection_slug slug=product.slug %}" title="Termék oldal">
                                <span class="product-element-name">{{ product.name }} | {{ product.price }} Ft.-</span>
                            </a>
                            <span class="product-element-collection">{{ product.get_collection.name }}</span>
                        </div>
                    </div>
                    {% endfor %}

                    <div class="clearfix"></div>

                    {% if page_obj.paginator.num_pages > 1 %}

                    {% include 'shop/_pagination.html' with page_obj=page_obj %}

                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                {% if gift_card %}
                        <div class="gift-card-wrapper">
                            <div class="gift-card-image-wrapper">
                                <img src="{% static 'images/giftcard.png' %}" alt="Ajándékkártya" title="Ajándékkártya" />
                            </div>
                            <div class="gift-card-description-wrapper">
                                <div class="gift-card-name">Ajándékkártya</div>
                                <div class="gift-card-price">5000 Ft.-</div>
                                <form action="{% url 'cart:cart_add_gift_card' 0 %}" method="post">
                                    <div class="gift-card-amount">
                                        <select required>
                                            {% for gc in gift_card %}
                                                <option value="{{ gc.price }}" data-id="{{ gc.id }}"
                                                        data-price="{{ gc.price }}">{{ gc.price }} Ft.-</option>
                                            {% endfor %}
                                            {{ card_gift_cart_product_form }}
                                            {% csrf_token %}
                                        </select>
                                    </div>
                                    <div class="gift-card-button-wrapper">
                                        <input id="add_to_cart_button" type="submit" value="Kosárba">
                                    </div>
                                </form>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    {% endif %}
                <div class="col-2"></div>
            </div>
    </div>
</div>
{% endblock %}

{% include 'shop/footer.html' with product_list=True %}

shop/templates/shop/product/detail.html
{% include "shop/base.html" with notification=notification product_details=True notfound=False seo_title=product.seo_title seo_description=product.seo_description device=device product=product follow=True %}
{% load static %}

{% block content %}
<div class="content product-detail">
    <div class="container-fluid">
        <div class="row detail-filter-row">
            <div id="detail-page-filter-button"></div>
            <div class="col-sm-3 detail-page-filter">
                <div id="mobile-filter-close"></div>
                {% include 'shop/product/filter.html' %}
            </div>
            <div class="col-sm-9">
                <div class="{% if types %}multi-product{% else %}single-product{% endif %} product-wrapper"
                     {% if not types %}data-stock="{{ product.stock }}"{% endif %}>
                    <div class="product-image-wrapper">
                        <div class="product-image">
                            <picture>
                              <source class="product_image" srcset="{{ product.image.url|wp }}" type="image/webp">
                              <img src="{{ product.image.url }}" alt="{% if product.seo_image_alt %}{{ product.seo_image_alt }}{% else %}{{ product.name }}{% endif %}"
                                   title="{{ product.name }} photo" class="product_image" width="625" height="625" style="aspect-ratio: 1;"/>
                            </picture>
                        </div>
                        <div class="product-thumbnails-wrapper">
                            <div class="product-thumbnail selected">
                                <picture>
                                  <source class="product_image" srcset="{{ product.image.url|wp }}" type="image/webp">
                                  <img src="{{ product.image.url }}" alt="{% if product.seo_image_alt %}{{ product.seo_image_alt }}{% else %}{{ product.name }}{% endif %}"
                                       title="{{ product.name }} thumbnail photo" class="product_image" width="625" height="625" style="aspect-ratio: 1;"/>
                                </picture>
                            </div>
                            {% if types %}
                                {% for type in types %}
                                    {% if type.image %}
                                    <div class="product-thumbnail">
                                        <picture>
                                          <source data-name="{{ type.color }}" srcset="{{ type.image.url|wp }}" type="image/webp">
                                          <img src="{{ type.image.url }}" alt="{% if type.seo_image_alt %}{{ type.seo_image_alt }}{% else %}{{ type.color }}{% endif %}"
                                               title="{{ product.name }} thumbnail photo" data-name="{{ type.color }}"  width="625" height="625" style="aspect-ratio: 1;"/>
                                        </picture>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                {% for img in images %}
                                    <div class="product-thumbnail">
                                        <picture>
                                          <source data-name="{{ type.color }}" srcset="{{ img.image.url|wp }}" type="image/webp">
                                          <img src="{{ img.image.url }}" alt="{% if product.seo_image_alt %}{{ product.seo_image_alt }}{% else %}{{ product.name }}{% endif %}"
                                               title="{{ product.name }} thumbnail photo" width="625" height="625" style="aspect-ratio: 1;" />
                                        </picture>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="product-description-wrapper">
                        <div class="product-name">
                            <h1>{% if product.product_name %}{{ product.product_name }}{% else %}{{ product.name }}{% endif %}</h1>
                        </div>
                        <div class="product-collection-name">
                            {{ product.get_collection.name }}
                        </div>
                        <div class="product-price">
                            {{ product.price }} Ft.-
                        </div>
                        <div class="product-interactions">
                            {% if is_stock %}
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                <div class="minus"><span>-</span></div>
                              {{ cart_product_form }}
                                <div class="plus"><span>+</span></div>
                              {% csrf_token %}
                                <input id="add_to_cart_button" type="submit" value="Kosárba">

                            </form>
                            {% else %}
                                <div id="out_of_stock_button"><span>Elfogyott</span></div>
                            {% endif %}
                        </div>
                        <div class="product-attributes">
                            {% if is_stock %}
                                <div class="product-attributes-color">
                                    {% if types %}
                                    <p>Szín:</p>
                                    <select required>
                                        <option value="" selected disabled>Válassz színt</option>
                                        {% for type in types %}
                                        {% if type.image %}
                                        <option value="{{ type.color }}" data-stock="{{ type.stock }}"
                                                data-img-src="{{ type.image.url }}"
                                                {% if type.stock == 0%}disabled{% endif %}>{{ type.color }}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                    {% endif %}
                                </div>
                            <div class="product-attributes-studs">
                                {% for stud in product.studs %}
                                <div>
                                    <label class="studs-container"><span class="label-text">{{ product|get_stud:stud }}</span>
                                    <input type="radio" {% if forloop.counter == 1 %}checked="checked"{% endif %}
                                           name="stud" value="{{ product|get_stud:stud }}" >
                                        <span class="checkmark"></span>
                                    </label>
                                    <picture class="stud-info">
                                      <source srcset="{% static 'images/info_icon.webp' %}" type="image/webp">
                                      <img src="{% static 'images/info_icon.png' %}"
                                           title="
                                           {% if stud == '1' %}
                                             {{ nemes_acel }}
                                           {% elif stud == '2' %}
                                             {{ nikkel_mentes }}
                                           {% else %}
                                             {{ muanyag }}
                                           {% endif %}" alt="info icon" width="15" height="15" style="aspect-ratio:15/15;"/>
                                    </picture>
                                    <div class="clearfix"></div>
                                </div>

                                {% endfor %}
                            </div>
                            {% if product.findings %}
                            <div class="product-attributes-findings">
                                <div class="product-question"><p>Más színű szerelékkel szeretnéd, mint amit a képen látsz? Válaszd ki!</p></div>
                                    {% for finding in product.findings_type %}
                                        <div>
                                            <label class="studs-container"><span class="label-text">{{ product|get_finding:finding }}</span>
                                            <input type="radio" {% if finding|make_string == product.default_finding_type|make_string %}checked="checked"{% endif %}
                                                   name="finding" value="{{ product|get_finding:finding }}" >
                                                <span class="checkmark"></span>
                                            </label>
                                            <div class="clearfix"></div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            {% endif %}
                            <div class="product-description">
                                <p>{{ product.description|linebreaksbr }}</p>
                                <br />
                                <p>{{ product.size|linebreaksbr }}</p>
                            </div>
                            <div id="color-info">
                                <p>Ez a termék bármilyen más, általad választott színben is rendelhető. Ehhez vedd fel velem a kapcsolatot <a href="{% url 'shop:contact' %}" title="Kapcsolat" >itt.</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="back-to-link">
                                <a href="{{ referer }}" title="Vissza a kollekcióhoz" alt="Vissza a kollekcióhoz">
                                    <img src="{% static 'images/arrow_left_150.png' %}" alt="Vissza a kollekcióhoz" title="Vissza a kollekcióhoz" width="50" height="33" style="aspect-ratio: 50/33;"/>
                                    <span>VISSZA A KOLLEKCIÓHOZ</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="button" id="error_button" class="btn btn-primary" data-toggle="modal" data-target="#errorModal">e</button>
        <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Hiba</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Értem</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

{% endblock %}

{% include 'shop/footer.html' with product_details=True %}