blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog-bejegyzesek'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

counter/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

# handler404 = 'shop.views.view_404'

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('order/', include('order.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('giftcard-payment/', include('giftcardpayment.urls', namespace='giftcardpayment')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.generic import TemplateView

from blog.sitemaps import BlogCategorySitemap, PostSitemap
from parameters.models import Parameter
from . import views
from .sitemaps import StaticViewsSitemap, CollectionSitemap, ProductSitemap

sitemaps = {
    'static': StaticViewsSitemap,
    'product': ProductSitemap,
    'collection': CollectionSitemap,
    'post': PostSitemap
}

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('termekek/', views.ProductsView.as_view(), name='products_view'),
    path('slowstudio/', views.StudioProductsView.as_view(), name='studio_products_view'),
    path('termekek/<str:slug>', views.ProductsView.as_view(), name='products_view'),
    path('termek/<str:id>/<str:slug>', views.product_detail, name='product_detail'),
    path('slowstudiotermek/<str:id>/<str:slug>', views.studio_product_detail, name='studio_product_detail'),
    path('gyik', views.faq, name='faq'),
    path('kapcsolat/', views.contact, name='contact'),
    path('aszf/', views.aszf, name='aszf'),
    path('adatvedelem/', views.data_handling, name='data_handling'),
    path('uzenet/', views.contact_message, name='contact_message'),
    path('sikeres-uzenet-kuldes/', views.thank_you, name='thank_you'),
    path('impresszum/', views.impresszum, name='impresszum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="shop/robots.txt", content_type='text/plain')),
    path('icon/', views.get_icon, name='get_icon'),
    path('generate_stripe_product/<str:id>', views.generate_stripe_product, name='generate_stripe_product'),
    path('termekek/kereses/', views.SearchProductsView.as_view(), name='products_view_search'),
    path('name-validation/<str:name>', views.name_validation, name='name-validation'),
    path('price-api-key/<str:price>', views.price_api_key, name='price-api-key'),
]

if Parameter.objects.filter(name="custom_service")[0].value == 'True':
    urlpatterns.extend([
        path('egyedi-rendelés/', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-rendelés/<str:slug>', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-termek/<str:id>/<str:slug>', views.custom_product_detail, name='custom_product_detail')
    ])

shop/forms.py
from django import forms
from django.forms import ModelForm

from .models import Message


class ContactForm(ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'email', 'message', 'name']
        widgets = dict(subject=forms.HiddenInput, email=forms.HiddenInput,
                       message=forms.HiddenInput, name=forms.HiddenInput)

shop/views.py
import json
import logging
import os
import re

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Case, When
from django.db.utils import OperationalError
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import redirect, reverse
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.views.generic.list import ListView

from cart.forms import CartAddProductForm, CartAddCustomProductForm, CartAddGiftCardProductForm
from parameters.models import Parameter
from shop.MessageSender import MessageSender
from .StripeProductGenerator import StripeProductGenerator
from .forms import ContactForm
from .models import Collection, Product, Notification, ProductType, GiftCard, Message

stripe_product_generator = StripeProductGenerator()
log = logging.getLogger(__name__)


def mobile(request):
    MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)
    if 'HTTP_USER_AGENT' in request.META and MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        return True
    else:
        return False


def index_hid(request):
    return render(request, 'shop/index.html')


def index(request):
    coll = Collection.objects.filter(available=True, custom=False, show_on_home_page=True)
    basic_collection = [c for c in coll if c.basic_collection and not c.best_seller_collection]
    temp = [c for c in coll if c.regular_collection and not c.best_seller_collection]
    regular_collections = sorted(temp, key=lambda x: x.created, reverse=True)[:3]
    temp = [c for c in coll if not c.basic_collection and not c.regular_collection and not c.best_seller_collection]
    temporary_collections = sorted(temp, key=lambda x: x.created, reverse=True)[:9]
    temp = [c for c in coll if c.best_seller_collection]
    best_sellers_collection = sorted(temp, key=lambda x: x.created)
    # basic_collection = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                              basic_collection=True, best_seller_collection=False)
    if len(basic_collection):
        basic_products = Product.objects.filter(collection=basic_collection[0])
    else:
        basic_products = []
    # regular_collections = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                                 regular_collection=True, best_seller_collection=False).order_by('-created')[:3]
    # temporary_collections = (
    #     Collection.objects.filter(available=True, custom=False, show_on_home_page=True, basic_collection=False,
    #                               regular_collection=False, best_seller_collection=False)
    #         .order_by('-created')[:9])
    # best_sellers_collection = Collection.objects.filter(available=True, custom=False, show_on_home_page=True,
    #                                                     best_seller_collection=True).order_by('-created')
    if len(best_sellers_collection):
        bs_products = Product.objects.filter(collection=best_sellers_collection[0])
    else:
        bs_products = []
    notification = Notification.objects.all()
    is_mobile = mobile(request)
    param = Parameter.objects.filter(name="shipping_information")
    shipping_information = param[0].value if len(param) and param[0].active else None
    ratio = 0.93 if is_mobile else 2.44
    context = dict(basic_collection=basic_collection, basic_products=basic_products,
                   regular_collections=regular_collections, temporary_collections=temporary_collections,
                   notification=notification, ratio=ratio, shipping_information=shipping_information,
                   best_sellers_collection=best_sellers_collection, bs_products=bs_products, device=mobile(request))
    return render(request, 'shop/index_hid.html', context)


def __get_product_details(request, id: str, slug: str, custom: bool, studio: bool, referer: str):
    old_collection = False
    try:
        collection = Collection.objects.filter(slug=id)[0]
    except (Collection.DoesNotExist, IndexError):
        log.info(f'Exception in getting product details - Collection slug {id}')
        return render(request, 'shop/404_termek.html', {})
    try:
        product = Product.objects.filter(collections=collection.id, slug=slug, available=True, custom=custom)[0]
    except (Product.DoesNotExist, IndexError):
        product = Product.objects.filter(collection=collection, slug=slug, available=True, custom=custom)
        if not len(product):
            log.info(f'Exception in getting product details - Product slug {slug}')
            return render(request, 'shop/404_termek.html', {})
        else:
            old_collection = True
            product = product[0]
    if old_collection:
        product_types = Product.objects.prefetch_related('product_types').filter(collection=collection, slug=slug,
                                                                                 available=True, custom=custom)
        images = Product.objects.prefetch_related('images').filter(collection=collection, slug=slug, available=True,
                                                                   custom=custom)
    else:
        product_types = Product.objects.prefetch_related('product_types').filter(collections=collection.id, slug=slug,
                                                                                 available=True, custom=custom)
        images = Product.objects.prefetch_related('images').filter(collections=collection.id, slug=slug, available=True,
                                                                   custom=custom)
    imgs = images[0].images.all()
    types = product_types[0].product_types.all()
    is_stock = False
    if types:
        for type in types:
            if type.stock > 0:
                is_stock = True
                break
    else:
        if product.stock > 0:
            is_stock = True
    cart_product_form = CartAddCustomProductForm() if custom else CartAddProductForm()
    basic_collections = [] if studio else Collection.objects.filter(
        available=True, basic_collection=True, custom=custom, studio_collection=False).order_by('-created')
    regular_collections = [] if studio else Collection.objects.filter(available=True, custom=custom,
                                                                      regular_collection=True,
                                                                      studio_collection=False).order_by('-created')
    temporary_collections = [] if studio else Collection.objects.filter(available=True, custom=custom,
                                                                        basic_collection=False,
                                                                        regular_collection=False,
                                                                        best_seller_collection=False,
                                                                        studio_collection=False).order_by('-created')
    # find if there is utolsó darabok
    temp = list(temporary_collections)
    upper = [e.name for e in temp if e.name.isupper()]
    if len(upper):
        idx_of_upper = [idx for idx, u in enumerate(temp) if u.name == upper[0]][0]
        temp.append(temp.pop(idx_of_upper))
    notification = Notification.objects.all()
    collection_slug = '' if studio else product.get_collection_slug()
    view = 'shop:studio_products_view' if studio else ('shop:custom_products_view' if custom else 'shop:products_view')
    template = 'shop/product/custom_detail.html' if custom else 'shop/product/detail.html'
    param = Parameter.objects.filter(name="shipping_information")
    nemes_acel = Parameter.objects.filter(name="nemesacel_beszuro")[0].value
    muanyag = Parameter.objects.filter(name="muanyag_beszuro")[0].value
    nikkel_mentes = Parameter.objects.filter(name="nikkel_mentes")[0].value
    shipping_information = param[0].value if len(param) and param[0].active else None
    if referer == settings.MAIN_URL or referer is None:
        if studio:
            referer = settings.MAIN_URL + 'slowstudio'
        else:
            referer = settings.MAIN_URL + 'termekek/' + product.get_collection_slug()
    return render(request, template,
                  {'product': product,
                   'notification': notification,
                   'basic_collections': basic_collections,
                   'regular_collections': regular_collections,
                   'temporary_collections': temp,
                   'collection_slug': collection_slug,
                   'types': types,
                   'cart_product_form': cart_product_form,
                   'is_stock': is_stock,
                   'images': imgs,
                   'view': view,
                   'slug': collection_slug,
                   'shipping_information': shipping_information,
                   'nemes_acel': nemes_acel,
                   'muanyag': muanyag,
                   'nikkel_mentes': nikkel_mentes,
                   'referer': referer,
                   'device': mobile(request)
                   })


def product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, False, False, referer)


def studio_product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, False, True, referer)


def custom_product_detail(request, id: str, slug: str):
    referer = request.META.get('HTTP_REFERER')
    return __get_product_details(request, id, slug, True, False, referer)


def faq(request):
    foxpost = Parameter.objects.filter(name="foxpost_price")[0].value
    delivery = Parameter.objects.filter(name="delivery_price")[0].value

shop/templates/shop/404_kollekcio.html
{% include "shop/base.html" with notification=notification notfound=True device=device %}
{% load static %}

{% block content %}
<div class="container not-found-page">
    <div>
        <h1>A keresett kollekció nem található!</h1>
    </div>
</div>

{% endblock %}

{% include 'shop/footer.html' with contact=True %}

shop/templates/shop/404_termek.html
{% include "shop/base.html" with notification=notification notfound=True device=device %}
{% load static %}

{% block content %}
<div class="container not-found-page">
    <div>
        <h1>A keresett termék nem található!</h1>
        <p>Amennyiben mégis szeretnél a termékről tájékoztatást kapni, esetleg rendelni,
            úgy kérlek küldj egy üzenetet a Kapcsolat linkre kattintva.</p>
        <p>Köszönöm</p>
    </div>
</div>

{% endblock %}

{% include 'shop/footer.html' with contact=True %}

shop/templates/shop/_pagination.html
{% load static %}

<div class="pagination">
    <div class="pagination-wrapper">
        <div class="pagination-inner">
            {% if page_obj.has_previous %}
            <a class="pagination-action" href="?page={{ page_obj.previous_page_number }}">
                <img class="previous-page" src="{% static 'images/arrow_left_150.png' %}"
                     alt="előző oldal" title="előző oldal" width="50" height="33" style="aspect-ratio: 50/33;"/>
            </a>
            {% else %}
            <img class="previous-page" src="{% static 'images/arrow_left_150.png' %}"
                     alt="előző oldal" title="előző oldal"  width="50" height="33" style="aspect-ratio: 50/33;"/>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <span class="pagination-number pagination-current">{{ num }}</span>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="pagination-number" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="pagination-action" href="?page={{ page_obj.next_page_number }}">
                    <img class="next-page" src="{% static 'images/arrow_right_150.png' %}"
                         alt="következő oldal" title="következő oldal"  width="50" height="33" style="aspect-ratio: 50/33;"/>
                </a>
            {% else %}
                <img class="next-page" src="{% static 'images/arrow_right_150.png' %}"
                             alt="következő oldal" title="következő oldal"  width="50" height="33" style="aspect-ratio: 50/33;"/>
            {% endif %}
        </div>
    </div>
</div>

shop/templates/shop/contact.html
{% include "shop/base.html" with notification=notification contact=True notfound=False seo_title=seo_title seo_description=seo_description device=device %}
{% load static %}

{% block content %}
<div id="contact-page">
    <div class="container-md">
        <div class="row">
            <div class="col-12">
                <form id="contact-form" action="{% url 'shop:contact_message' %}" method="post">
                    <div class="form-group">
                        <label for="contact-name">Név*</label>
                        <input type="text" class="form-control" id="contact-name" name="contact-name" required>
                    </div>
                    <div class="form-group">
                        <label for="contact-email">E-mail cím*</label>
                        <input type="email" class="form-control" id="contact-email" name="contact-email" required>
                    </div>
                    <div class="form-group">
                        <label for="contact-subject">Tárgy</label>
                        <input type="text" class="form-control" id="contact-subject" name="contact-subject">
                    </div>
                    <div class="form-group">
                        <label for="contact-message">Üzenet*</label>
                        <textarea class="form-control" id="contact-message" name="contact-message"
                                  rows="4" maxlength="2000" required></textarea>
                    </div>
                    {{ contact_form }}
                    {% csrf_token %}
                    <div class="text-center">
                        <input type="submit" form="contact-form" value="Küldés" id="contact-submit" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% include 'shop/footer.html' with contact=True %}

shop/templates/shop/footer.html
{% load static %}
{% spaceless %}
<footer>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div id="submark-logo-wrapper">
                    <a href="{% url 'shop:index' %}">
                        <picture>
                          <source srcset="{% static 'images/submark_150.webp' %}" type="image/webp">
                          <img src="{% static 'images/submark_150.png' %}" alt="Minerva Logo" title="Minerva Logo image" width="200" height="200" style="aspect-ratio:200/200;" loading="lazy">
                        </picture>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div id="social">
                    <div id="facebook">
                        <a href="https://www.facebook.com/minervastudio.hu">
                            <picture>
                              <source srcset="{% static 'images/facebook_150.webp' %}" type="image/webp">
                              <img src="{% static 'images/facebook_150.png' %}" alt="facebook icon" title="facebook icon image" width="65" height="65" style="aspect-ratio:65/65;" loading="lazy"/>
                            </picture>
                        </a>
                    </div>
                    <div id="instagram">
                        <a href="https://www.instagram.com/minervastudio.hu/">
                            <picture>
                              <source srcset="{% static 'images/instagram_150.webp' %}" type="image/webp">
                              <img src="{% static 'images/instagram_150.png' %}" alt="instagram icon" title="instagram icon" width="65" height="65" style="aspect-ratio:65/65;" loading="lazy"/>
                            </picture>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row navigation-row" {% if request.path != '/' %}style="background: #FCEDE4;"{% endif %}>
            <div class="col-sm-12">
                <div class="navigation">
                    <ul class="mainmenu">
                        <li class="menu-item">
                            <a title="Termékek" href="{% url 'shop:products_view' %}" >Termékek</a>
                        </li>
                        <li class="menu-item">
                            <a title="GYIK" href="{% url 'shop:faq' %}" >GYIK</a>
                        </li>
                        <li class="menu-item">
                            <a title="Kapcsolat" href="{% url 'shop:contact' %}" >Kapcsolat</a>
                        </li>
                        {% if CUSTOM %}
                        <li class="menu-item">
                            <a title="Egyedi rendelés" href="{% url 'shop:custom_products_view' %}" >Egyedi rendelés</a>
                          </li>
                        {% endif %}
                        <li class="menu-item">
                            <a title="ÁSZF" href="{% url 'shop:aszf' %}" >ÁSZF</a>
                        </li>
                        <li class="menu-item">
                            <a title="Impresszum" href="{% url 'shop:impresszum' %}" >Impresszum</a>
                        </li>
                        <li class="menu-item">
                            <a title="Adatkezelési Tájékoztató" href="{% url 'shop:data_handling' %}" >Adatkezelési Tájékoztató</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
{% if shipping_information != None %}
<section id="information-consent" class="information-consent">
    <div class="information-consent-inner">
        <div class="information">
            <div class="information-inner">
                <div class="information-msg">Kedves látogató! <br />{{ shipping_information }}</div>
                <div class="information-accept">
                    <button id="information" class="information-button" onclick='SetInfoAndHideDiv();'>Értem</button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}
<section id="cookie-consent" class="cookie-consent">
	<div class="cookie-consent-inner">
		<div class="cookie">

			<div class="cookie-msg">Kedves látogató. Tájékoztatlak, hogy a honlap felhasználói élmény fokázásnak érdekében sütiket alkalmazunk. A honlap használatával a tájékoztatást tudomásul veszed.</div>
			<div class="cookie-accept">
				<button id="cookie" class="cookie-button" onclick='SetCookieAndHideDiv();'>OK</button>
			</div>

		</div>
	</div>
</section>
{% if home %}
    <script src="{% static 'js/owl.carousel.min.js' %}" defer ></script>
    <script src="{% static 'js/home_page_carousel.js' %}" defer></script>
    <script src="{% static 'js/home.js' %}" defer></script>
{% endif %}
<script src="{% static 'js/popper.min.js' %}" defer></script>
<script src="{% static "js/js.cookie.min.js" %}" defer></script>
<script>
jQuery.event.special.touchstart = {
    setup: function( _, ns, handle ) {
        this.addEventListener("touchstart", handle, { passive: !ns.includes("noPreventDefault") });
    }
};
jQuery.event.special.touchmove = {
    setup: function( _, ns, handle ) {
        this.addEventListener("touchmove", handle, { passive: !ns.includes("noPreventDefault") });
    }
};
</script>
<script src="{% static 'js/bootstrap.min.js' %}" defer></script>
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<script src="{% static 'js/main_v2.js' %}" defer></script>
<script src="{% static 'js/cookies.js' %}" defer></script>
{% if stripe %}
    <script src="https://js.stripe.com/v3/" defer></script>
    <script src="{% static 'js/stripe_payment.js' %}" defer></script>
{% endif %}
{% if contact %}
    <script src="{% static 'js/contact.js' %}" defer></script>
{% endif %}
{% if product_list %}
    <script src="{% static 'js/product_list.js' %}" defer></script>
{% endif %}
{% if product_details %}
    <script src="{% static 'js/product_details_v2.js' %}" defer></script>
{% endif %}
{% if cart_page %}
    <script src="{% static 'js/cart_v2.js' %}" defer></script>
{% endif %}
  </body>
</html>
{% endspaceless %}

shop/templates/shop/impresszum.html
{% include "shop/base.html" with notification=notification impresszum=True notfound=False device=device %}
{% load static %}

{% block content %}
<div id="content" class="impresszum">
    <div class="container">
        <div class="col-sm-12">
            <h1>IMPRESSZUM</h1>
                <p>Cégnév: Kakuszi Bettina e.v.</p>
                <p>Székhely: 6722 Szeged, Mars tér 17. 2/12</p>
                <p>Telefon: +36 70 236 7315</p>
                <p>E-mail: minervaearrings@gmail.com</p>
                <p>Webcím: www.minervastudio.hu</p>
                <p>Adószám: 56628829-1-26</p>
                <p>Nyilvántartási szám: 55295718</p>
                <p>Kamara: Csongrád megyei Kereskedelmi és Iparkamara</p>
                <p>Tárhelyszolgáltató: https://www.pythonanywhere.com/</p>
        </div>
    </div>
</div>

{% endblock %}

{% include 'shop/footer.html' with contact=True %}

shop/templates/shop/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Minerva Studio</title>
    <link href="{% static "css/counter.css" %}" rel="stylesheet" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <header id="header">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="notification-wrapper">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div id="main-logo">
              <a href="{% url 'shop:index' %}">
                  <img class="c_logo" src="{% static 'images/submark_150.png' %}" alt="Minerva Studio Logo" title="Minerva Studio Logo"/>
              </a>
            </div>
          </div>
        </div>
      </div>
    </header>

    <div id="content">
        <section id="content-title">
            <div class="container">
                <div class="row">
                    <div id="top-text">
                        <h1>Hamarosan</h1>
                    </div>
                    <div id="bottom-text">
                        <h2>elérhetőek leszünk!</h2>
                    </div>
                </div>
            </div>
        </section>
<!--        <section id="counter">-->
<!--            <span id="time">99:00</span>-->
<!--        </section>-->
    </div>

  <footer>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div id="social">
                    <div id="facebook">
                        <a href="https://www.facebook.com/minervastudio.hu">
                            <img src="{% static 'images/facebook_150.png' %}" alt="facebook icon" title="facebook icon" />
                        </a>
                    </div>
                    <div id="instagram">
                        <a href="https://www.instagram.com/minervastudio.hu/">
                            <img src="{% static 'images/instagram_150.png' %}" alt="instagram icon" title="instagram icon" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link rel="preload" as="font" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin>
    <script src="{% static 'js/countdown.js' %}"></script>
  </body>
</html>

shop/templates/shop/thank_you.html
{% include "shop/base.html" with notification=notification payment=True notfound=False device=device %}
{% load static %}

{% block content %}
<div id="payment-result-container">
  <div class="container-fluid">
    <div class="row">
        <div class="col-12">
          <div class="success-wrapper">
            <div class="success-icon">
              <img src="{% static 'images/tick.png' %}" alt="Sikeres üzenetküldés" title="Sikeres üzenetküldés" />
            </div>
            <div class="success-text">
              <p>Üzeneted sikeresen eljutott hozzám.</p>
              <p>A válasszal hamarosan a megadott e-mailen keresztül foglak megkeresni.</p>
            </div>
            <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% include 'shop/footer.html' %}