blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog-bejegyzesek'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

counter/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

# handler404 = 'shop.views.view_404'

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('order/', include('order.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('giftcard-payment/', include('giftcardpayment.urls', namespace='giftcardpayment')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('done/', views.payment_done, name='done'),
    # path('cancelled/', views.payment_cancelled, name='cancelled'),
    path('process/config/', views.stripe_config),
    path('process/create-checkout-session/', views.create_checkout_session),
    path('success/', views.SuccessView.as_view()),
    path('cancelled/', views.CancelledView.as_view(), name='cancelled'),
    path('webhook/', views.stripe_webhook),
    path('finalize_gift_card_payment/', views.finalize_gift_card_payment, name='finalize_gift_card_payment'),
]

shop/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.generic import TemplateView

from blog.sitemaps import BlogCategorySitemap, PostSitemap
from parameters.models import Parameter
from . import views
from .sitemaps import StaticViewsSitemap, CollectionSitemap, ProductSitemap

sitemaps = {
    'static': StaticViewsSitemap,
    'product': ProductSitemap,
    'collection': CollectionSitemap,
    'post': PostSitemap
}

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('termekek/', views.ProductsView.as_view(), name='products_view'),
    path('slowstudio/', views.StudioProductsView.as_view(), name='studio_products_view'),
    path('termekek/<str:slug>', views.ProductsView.as_view(), name='products_view'),
    path('termek/<str:id>/<str:slug>', views.product_detail, name='product_detail'),
    path('slowstudiotermek/<str:id>/<str:slug>', views.studio_product_detail, name='studio_product_detail'),
    path('gyik', views.faq, name='faq'),
    path('kapcsolat/', views.contact, name='contact'),
    path('aszf/', views.aszf, name='aszf'),
    path('adatvedelem/', views.data_handling, name='data_handling'),
    path('uzenet/', views.contact_message, name='contact_message'),
    path('sikeres-uzenet-kuldes/', views.thank_you, name='thank_you'),
    path('impresszum/', views.impresszum, name='impresszum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="shop/robots.txt", content_type='text/plain')),
    path('icon/', views.get_icon, name='get_icon'),
    path('generate_stripe_product/<str:id>', views.generate_stripe_product, name='generate_stripe_product'),
    path('termekek/kereses/', views.SearchProductsView.as_view(), name='products_view_search'),
    path('name-validation/<str:name>', views.name_validation, name='name-validation'),
    path('price-api-key/<str:price>', views.price_api_key, name='price-api-key'),
]

if Parameter.objects.filter(name="custom_service")[0].value == 'True':
    urlpatterns.extend([
        path('egyedi-rendelés/', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-rendelés/<str:slug>', views.CustomProductsView.as_view(), name='custom_products_view'),
        path('egyedi-termek/<str:id>/<str:slug>', views.custom_product_detail, name='custom_product_detail')
    ])

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import json
from datetime import datetime, timedelta
from smtplib import SMTPAuthenticationError

import stripe
from django.conf import settings
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from cart.cart import Cart
from giftcardpayment.models import BoughtGiftCard
from logs.models import LogFile
from order.models import Order
from parameters.models import Parameter
from shop.MessageSender import MessageSender
from shop.models import Notification, Product, GiftCard, Message


def __create_log_file(message: str, type_: str = 'INFO'):
    log = LogFile(type=type_, message=message)
    log.save()


@csrf_exempt
def payment_done(request):
    cart = Cart(request)
    cart.clear()
    notification = Notification.objects.all()
    return render(request, 'payment/done.html', {'notification': notification})


@csrf_exempt
def payment_cancelled(request):
    notification = Notification.objects.all()
    return render(request, 'payment/cancelled.html', {'notification': notification})


def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'payment/process.html', {'order': order})


@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)


@csrf_exempt
def create_checkout_session(request):
    order_id = request.session.get('order_id')
    cart = Cart(request)
    items = []
    order = Order.objects.prefetch_related('items').filter(id=order_id)
    discount = ''
    metadata = dict(order_id=order_id)
    # if any gift card is applied an add hoc payment is created
    # this sucks since 175ft is the minimum limit for a purchase
    if hasattr(cart, 'gift_cards') and cart.gift_cards is not None:
        total_price = cart.calculated_total_price()
        items.append(dict(name='Ajándékkártya', amount=int(total_price) * 100, quantity=1,
                          currency=Parameter.objects.filter(name="currency")[0].value))
    else:
        discount = order[0].coupon if order[0].coupon is not None else ''
        for k, v in cart.cart.items():
            if v.get('product_id') is not None:
                product = Product.objects.filter(id=v.get('product_id'))[0]
                if Parameter.objects.filter(name="discount_service")[0].value == 'True':
                    if v['zero_discount']:
                        if int(v['discount_show_price']) != 0:
                            q = v['discount_quantity']
                            if q > 0:
                                items.append(dict(price=product.price_api_id, quantity=int(q)))
                    else:
                        items.append(dict(price=product.price_api_id, quantity=int(v.get('quantity'))))
                else:
                    items.append(dict(price=product.price_api_id, quantity=int(v.get('quantity'))))
            else:
                gift_card = GiftCard.objects.filter(id=v.get('gift_card_id'))[0]
                items.append(dict(price=gift_card.price_api_id, quantity=int(v.get('quantity'))))
        delivery_type = order[0].delivery_type
        if delivery_type == 'Házhozszállítás':
            items.append(dict(price=Parameter.objects.filter(name="delivery_price_api_key")[0].value, quantity=1))
        elif delivery_type == 'FoxPost':
            items.append(dict(price=Parameter.objects.filter(name="foxpost_price_api_key")[0].value, quantity=1))
        elif delivery_type == 'Csomagkuldo':
            items.append(dict(price=Parameter.objects.filter(name="csomagkuldo_price_api_key")[0].value, quantity=1))
        elif delivery_type == 'Ajanlott':
            items.append(dict(price=Parameter.objects.filter(name="ajanlott_price_api_key")[0].value, quantity=1))
        if cart.gift_card_ids:
            if len(cart.gift_card_ids) > 0:
                pass

    if request.method == 'GET':
        domain_url = settings.BASE_URL
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            checkout_session = stripe.checkout.Session.create(
                success_url=domain_url + reverse('payment:done') + '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=domain_url + reverse('payment:cancelled'),
                payment_method_types=['card'],
                mode='payment',
                metadata=metadata,
                line_items=items,
                **({"discounts": [dict(coupon=discount)]} if discount != '' else {}),
            )
            return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)})


class SuccessView(TemplateView):
    template_name = 'payment/success.html'


class CancelledView(TemplateView):
    template_name = 'payment/cancelled.html'


def __save_order(event, order, prices):
    order.paid = True
    order.paid_by = 'Stripe'
    order.paid_time = (datetime.utcfromtimestamp(event['created'])
                       + timedelta(hours=1)).strftime('%Y-%m-%d %H:%M:%S')
    order.delivery_cost = prices[order.delivery_type.replace(' ', '')]
    order.save()


def __save_order_items(order):
    for o in order.items.all():
        if o.product is not None and not o.product.custom:
            product = Product.objects.prefetch_related('product_types').filter(id=o.product.id)[0]
            if len(product.product_types.all()) > 0:
                product_type = [pt for pt in product.product_types.all() if pt.color == o.color]
                msg = f'Stock of product with the ID of "{product.id}" and the name of "{product.name}" and the' \
                      f' color of "{product_type[0].color}" was decreased with {o.quantity}. ' \
                      f'Previous stock was "{product_type[0].stock}", '
                product_type[0].stock = product_type[0].stock - o.quantity
                product_type[0].save()
                msg += f'current stock is "{product_type[0].stock}". Order ID: {order.id}'
                __create_log_file(msg)
            else:
                msg = f'Stock of product with the ID of "{product.id}" and the name of "{product.name}" was ' \
                      f'decreased with {o.quantity}. Previous stock was "{product.stock}", current stock is '
                product.stock = product.stock - o.quantity
                msg += f'"{product.stock}". Order ID: {order.id}'
                __create_log_file(msg)
            product.save()
        if o.gift_card is not None:
            gift_card = GiftCard.objects.get(id=o.gift_card.id)
            bought_card = BoughtGiftCard(price=gift_card.price, bought=datetime.now, email=order.email, active=True)
            bought_card.save()


def __send_order_confirmation_email(o, prices):
    order_data = {'Szállítási név': o.delivery_name, 'Szállítási cím': o.address,
                  'Házszám, emelet, ajtó': o.address_number,
                  'Postakód': o.postal_code, 'Település': o.city, 'Megjegyzés': o.note}
    delivery_info = dict(FoxPost={'Átvételi pont': o.fox_post},
                         Csomagkuldo={'Átvételi pont': o.csomagkuldo},
                         Házhozszállítás=order_data,
                         Ajanlott=order_data,
                         Személyesátvétel={'Vezetéknév': o.first_name, 'Keresztnév': o.last_name})
    delivery_price = prices[o.delivery_type.replace(' ', '')]
    delivery_data = delivery_info[o.delivery_type.replace(' ', '')]
    order_total = o.total
    data = {'name': o.full_name, 'order': o,
            'delivery_price': delivery_price,
            'delivery_info': delivery_data,
            'order_total': order_total}
    subject = f'Rendelés megerősítése #{str(o.id)}'
    sender = 'www.minervastudio.hu'
    try:
        result, msg = MessageSender(subject=subject, to=o.email, sender=sender).send_order_confirmation_email(data)
        sent = True if result == 1 else False
    except SMTPAuthenticationError:
        msg = f'Could not send order confirmation message to the following order id: "{str(o.id)}"'
        __create_log_file(type_='ERROR', message=msg)
        sent = 0
    Message.objects.create(subject=f'Rendelés megerősítése #{str(o.id)}', email=o.email, message=msg,
                           sender='System message from Minerva Studio', sent=sent)


def __send_email_about_the_order(o):
    product = ', '.join([i.product.name for i in o.items.all()])
    msg = f'Új rendelés:\nA rendelés száma: #{str(o.id)}\nA rendelés összege: {str(o.total)} Ft\nTermékek: {product}'
    subject = f'Új rendelés #{str(o.id)}'
    sender = 'www.minervastudio.hu'
    try:
        result = MessageSender(subject=subject, to=settings.EMAIL_HOST_USER, sender=sender, message=msg).send_mail()
        sent = True if result == 1 else False
    except SMTPAuthenticationError:
        msg = f'Could not send email about the order to the following order id: "{str(o.id)}"'
        __create_log_file(type_='ERROR', message=msg)
        sent = 0
    __create_log_file(f'Message is sent to "{o.email}", status: "{sent}"')
    Message.objects.create(subject=f'Új rendelés #{str(o.id)}', email=settings.EMAIL_HOST_USER, message=msg,
                           sender='System message from Minerva Studio', sent=sent)


def __post_payment_process(event):
    prices = dict(FoxPost=int(Parameter.objects.filter(name="foxpost_price")[0].value),
                  Csomagkuldo=int(Parameter.objects.filter(name="csomagkuldo_price")[0].value),
                  Házhozszállítás=int(Parameter.objects.filter(name="delivery_price")[0].value),
                  Személyesátvétel=0,
                  Ajanlott=int(Parameter.objects.filter(name="ajanlott_price")[0].value))

payment/templates/payment/cancelled.html
{% include "shop/base.html" with notification=notification payment=True notfound=False %}
{% load static %}

{% block content %}
<div id="payment-result-container">
  <div class="container-fluid">
    <div class="row">
        <div class="col-12">
          <div class="success-wrapper">
            <div class="success-icon">
              <img src="{% static 'images/untick.png' %}" alt="Sikertelen vásárlás" title="Sikertelen vásárlás" />
            </div>
            <div class="success-text">
              <p>Sikertelen megrendelés!</p>
              <p>Kérlek, ellenőrizd a bankkártya adataid és próbáld újra.</p>
            </div>
            <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% include 'shop/footer.html' %}

payment/templates/payment/done.html
{% include "shop/base.html" with notification=notification payment=True notfound=False %}
{% load static %}

{% block content %}
<div id="payment-result-container">
  <div class="container-fluid">
    <div class="row">
        <div class="col-12">
          <div class="success-wrapper">
            <div class="success-icon">
              <img src="{% static 'images/tick.png' %}" alt="Sikeres vásárlás" title="Sikeres vásárlás" />
            </div>
            <div class="success-text">
              <p>Sikeres megrendelés!</p>
              <p>A megerősítő e-mailt a rendelés részletes adataival a megadott e-mail címre küldjük ki.</p>
            </div>
            <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% include 'shop/footer.html' %}

payment/templates/payment/process.html
{% include "shop/base.html" with notification=notification cart_page=True payment=True notfound=False %}
{% load static %}

{% block content %}
  <div class="container process-page">
      <div class="row">
          <div class="col-12">
              <div id="cart-header">
                <h1 >ELLENŐRZÉS</h1>
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-sm-12">
              <p class="info">Az általad megadott adatok a következőek:</p>
              <div class="check-form">
                  <div class="check-form-key">
                      Név:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.full_name }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      E-mail:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.email }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Telefonszám:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.phone }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Megjegyzés:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.product_note }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Kiválasztott szállítási mód:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.delivery_type }}</p>
                  </div>
                  <div class="clearfix"></div>
                  {% if order.delivery_type == 'Személyes átvétel' %}
                  <div class="check-form-key">
                      Vezetéknév:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.first_name }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Keresztnév:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.last_name }}</p>
                  </div>
                  <div class="clearfix"></div>
                  {% elif order.delivery_type == 'Csomagkuldo' %}
                  <div class="check-form-key">
                      Csomag átvételi pont:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.csomagkuldo }}</p>
                  </div>
                  <div class="clearfix"></div>
                  {% elif order.delivery_type == 'FoxPost' %}
                  <div class="check-form-key">
                      Csomag átvételi pont:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.fox_post }}</p>
                  </div>
                  <div class="clearfix"></div>
                  {% else %}
                  <div class="check-form-key">
                      Szállítási név:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.delivery_name }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Utca:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.address }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Házszám:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.address_number }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Irányítószám:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.postal_code }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Település:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.city }}</p>
                  </div>
                  <div class="clearfix"></div>
                  <div class="check-form-key">
                      Szállítási megjegyzés:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.note }}</p>
                  </div>
                  <div class="clearfix"></div>
                  {% endif %}
                  {% if order.coupon %}
                  <div class="check-form-key">
                      Felhasznált kupon:
                  </div>
                  <div class="check-form-value">
                      <p>{{ order.coupon }}</p>
                  </div>
                  <div class="clearfix"></div>
                  {% endif %}
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-12">
              <div id="end-total">
                <div class="end-total-wrapper">
                    <div id="end-total-text">
                      <p>Összesen fizetendő:</p>
                    </div>
                    <div id="end-total-amount">
                      <p id="total_price" data-price="{{ cart.calculated_total_price|floatformat:0 }}">
                          {{ cart.calculated_total_price|floatformat:"0" }} Ft</p>
                    </div>
                  <div class="clearfix"></div>
                </div>
              </div>
          </div>
      </div>
      <div class="row confirmation-row">
          <div class="col-12">
              <form onsubmit="event.preventDefault();" id="confirmation-form">
                  <div class="data-alert">
                      <p>A személyes adatokat a rendelés teljesítéséhez, a weboldalon történő vásárlási élmény
                          fenntartásához és egyéb célokra használjuk, melyeket
                          <a href="{% url 'shop:data_handling' %}" title="adatkezelési nyilatkozat">az adatkezelési nyilatkozat</a>
                          tartalmaz.</p>
                  </div>
                  <div class="aszf-confirmation">
                      <div class="form-check">
                          <input type="checkbox" class="form-check-input" id="aszf-check" required>
                          <label class="form-check-label" for="aszf-check">Elolvastam és elfogadom az
                              <a href="{% url 'shop:aszf' %}" title="általános szerződési feltételek">
                                  Általános Szerződési Feltételek</a>-ben foglaltakat.<span style="color:red;">*</span></label>
                      </div>
                  </div>
              </form>
          </div>
      </div>
      <div class="row">
          <div class="col-12">
              <div id="purchase-button-wrapper">
                  {% if cart.calculated_total_price != 0 %}
                  <button class="button is-primary" id="submitBtn">FIZETÉS</button>
                  {% else %}
                  <form action="{% url 'payment:finalize_gift_card_payment' %}" method="post">
                      {% csrf_token %}
                      <input type="hidden" value="{{ order.id }}" name="order_id" />
                      <button class="button is-primary" id="submit-gift-card">Megrendelem</button>
                  </form>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>

{% endblock %}

{% include 'shop/footer.html' with stripe=True %}

payment/templates/payment/success.html
{% include "shop/base.html" with notification=notification notfound=False %}
{% load static %}

{% block content %}
<section class="section">
<div class="container">
  <p>Your payment succeeded.</p>
</div>
</section>

{% endblock %}

{% include 'shop/footer.html' %}